remote_theme: fongandrew/hydeout


title:      'E4-Notes'
tagline:    'A collection of notes on Electronics IV'
url:        https://k3rn3l-pan1c.github.io/E4-notes/

author:
   name:    'Pedro Martins'
#  url: 


sidebar_home_link: true


github:
   repo: https://github.com/k3rn3l-pan1c/E4-notes

